# Promise回调之间的关系

多个人处理一个结果

```
axios({
    url:'xxx'
}).then(s1,e1)    //第一责任人
    .then(s2,e2)  //第二责任人
    .then(s3,e3)  //第三责任人
```

假设第一次结果成果，s1一定会被调用，s2是否会调用看s1怎么处理（也就是return 出来的值）。如果第一责任人出现差错，第二责任人就会当做失败处理，如果第二责任人也没有处理，那么错误会抛出给开发者。

# 自己写Promise

Promise形式

```apple js
function ajax(){
    return new Promise((resolve, reject)=>{
        //做事
        //如果成功就调用 resolve
        //如果失败就调用 reject
    })
}

var promise = ajax()
promise.then(successFn, errorFn)
```

```apple js
buyFruit(){
  return new Promise((x,y)=>{
    setTimeout(()=>{
      x('apple')
    },1000)
  })
}

var promise = buyFruit()

promise.then()
```

# async/await

await 后面接一个返回Promise的函数。

```apple js
//result会等buyFruit成功之后的结果再执行
//类似与模拟同步的代码
//如果执行失败会直接报错，可以用try-catch
var result = await buyFruit()
```


```apple js
//如果函数里面有await  需要在外面加一个async
async function  fn(){
  var result = await buyFruit()
  return result
} 
  
var s= await fn()
console.log(2)
```
# 自拟一个简单的Promise
```apple js
function Promise(fn){
  var status = 'pending'
  var successArr = []
  var failedArr = []
  
  function resolve(){
    status = 'resolve'
    doSth.apply(undefined,arguments)
  }
  function reject(){
    status = 'reject'
    doSth.apply(undefined,arguments)
  }
  
  function doSth(){
    setTimeout(()=>{
      if(status === 'resolve'){
        for(let i=0;i<successArr.length;i++){
          successArr[i].apply(undefined,arguments)
        }
      }else if(status==='reject'){
        for(let i=0;i<failedArr.length;i++){
          failedArr[i].apply(undefined,arguments)
        }
      }
    },0)
  }
  //自动启动事务
  fn.call(undefined,resolve,reject)
  return {
    //事务存储队列
    then:function(successFn,failedFn){
      successArr.push(successFn)
      failedArr.push(failedFn)
      //正常应该返回一个Promise
      return undefined
    }
  }
}

var promise = new Promise(function(x,y){
    setTimeout(()=>{
        x(101)
    }, 3000)
})
promise.then((z)=>{
    console.log(z)  // 101
})
```